# Generated by Django 3.2 on 2023-09-01 09:44

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.UsernameValidator(), users.validators.no_me_as_username_allowed], verbose_name='Имя пользователя'),
        ),
    ]
