# Generated by Django 3.2 on 2023-08-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0002_alter_titles_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(related_name='titles', to='titles.Genres'),
        ),
    ]
